main:
		g++ BussinessLayer/main.cpp BussinessLayer/D2Shape/D2Circle.cpp BussinessLayer/D3Shape/D3Circle.cpp  BussinessLayer/D2Shape/D2Rectangle.cpp BussinessLayer/D3Shape/D3Rectangle.cpp BussinessLayer/D2Shape/D2Factory.cpp BussinessLayer/D3Shape/D3Factory.cpp BussinessLayer/getFactory.cpp BussinessLayer/saveObject.cpp BussinessLayer/drawProgram.cpp BussinessLayer/factoryMaker.cpp PresentationLayer/showMenu.cpp -o main
clean:
	rm *.cpp main