main: 
	g++ PresentationLayer/showReservation.cpp BussinessLayer/setupReservation.cpp  DataLayer/saveReservation.cpp  src/passenger.cpp src/ticket.cpp src/AccessMode.cpp src/main.cpp -o main

clean:
	rm *.cpp main

